### ISSUE TITLE
#### Deprecated packages

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#13151]
**Estimate:** 1 week

**Owner:** @skinny85

Remove all deprecated packages from `aws-cdk-lib`. 

**Tasks:**
- [ ] configure `monocdk` with a list of deprecated packages that it already excludes and do not allow anymore. update `ubergen` script to recognize this.
- [ ] mark all other packages as `deprecated: true` in `package.json` so that it's excluded from `aws-cdk-lib`.
- [ ] add an awslint rule that packages whose `stability` is `deprecated` should also have `deprecated: true` set.
