### ISSUE TITLE
New API Reference Experience

### ISSUE THREAD

**Issue by fulghum** [aws/aws-cdk#1666]
Prototype a new experience for the API Reference to help developers understand the areas of the AWS Construct Library, find sample code, easily understand which components/APIs are experimental/dev-preview/etc.  

Consider API versioning and deep linking, too. 

------------

Preview: http://aws-cdk-refdocs.s3-website-us-east-1.amazonaws.com/

TODO

**CDK reference**
- [x] Versioning
- [x] Lorem ipsum...
- [ ] CDK reference: AWS aspects
- [x] CDK reference: prettier layout.
- [x] CDK reference: list implementors of classes
- [x] Non-resource classes.
- [x] Link to lang-specific refs from top bar
- [x] Reference styling
- [x] Library maturity badges
- [x] Experimentality badges
- [ ] Fold keyword arguments into method reference

**TypeScript**
- [x] Get rid of "Sharepoint framework reference"
- [x] Sometimes wrong template
- [ ] Some pages are empty -- caused by CfnFoo namespaces and classes having the same name
- [ ] deeplinks back to CDK reference
- [ ] Handle defaults correctly
- [ ] Interface inheritance not shown
- [ ] Lists in MarkDown are not rendered correctly.

**.NET**
- [x] Useless/JSII-based members show up
- [ ] Deeplinks back to CDK reference

**Other**
- [ ] .NET/TypeScript: visually distinguish references from each other
- [ ] Double backticks in doc comments
- [ ] Build tests

**Comment by rix0rrr** [comment]
# Questions to be answered

* Reference docs in every language's native code generator, or using a single shared code generator?
* Hosted up on docs.aws.amazon.com, or hosted somewhere else?

**Comment by eladb** [comment]
@rix0rrr have you been possessed by aliens?

**Comment by rix0rrr** [comment]
Still relevant
