### ISSUE TITLE
(cli): add policy validation at synth time

### ISSUE THREAD

**Issue by otaviomacedo** [aws/aws-cdk#23756]
### Describe the feature

Allow users to define policies using common policy-as-code tools such as CloudFormation Guard, OPA and Checkov. At synth time, if the generated CloudFormation template doesn't comply with the specified policy, fail the synthesis.

### Use Case

Having to wait a long time to know whether your infrastructure violates some centrally defined policy hurts developer productivity. By checking at synth time, we shift the validation left and shorten the feedback loop.

### Proposed Solution

* [x] Write an RFC.
* [x] Define a plugin interface (take into account different tools for future proofing)
* [ ] Implement policy fetching
* [ ] Implement the validation flow (to call the plugin)
* [ ] Implement a plugin loader
* [ ] Implement the CFN Guard integration
* [ ] Write CLI integration tests
* [ ] Implement a trace back mechanism for error reporting. Requires investigation.
* [ ] Implement a rule suppression mechanism (e.g., by writing metadata to the template). Leave this to each plugin.
* [ ] README.
* [ ] Blog post.
* [ ] Documentation on the AWS website. Probably start out as a wiki in the repo.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by evgenyka** [comment]
I think we should not fail synthesize (since the validation will be done on the templates themselves), but provide the detailed and tradable report and remediation steps, where it is possible.
