### ISSUE TITLE
Assertions for AwsCustomResource integ tests (1/2)

### ISSUE THREAD

**Issue by colifran** [aws/aws-cdk#29937]
### Context

The AWS SDK V2 is being deprecated. We need to remove all uses of it from the CDK. As a result, the SDK v2 handler used by `AwsCustomResource` is being removed. Several integ tests are impacted due to the changing asset hash and it was noted that none of these integ tests have assertions related to `AwsCustomResource`. To improve testing coverage we will be adding assertions to these integ tests.

### Task Description

Update integ tests impacted by the removal of the SDK v2 handler to include assertions for `AwsCustomResource` where possible. Note that in some cases an assertion is not possible. For example, where the `AwsCustomResource` is making a `describe` related API call there will be nothing to assert against.

### Acceptance Criteria

Investigate the following integ tests and add assertions where possible:
- [x] @aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2/test/integ.alb.oidc.ts
- [x] @aws-cdk-testing/framework-integ/test/aws-elasticloadbalancingv2-actions/test/integ.cognito.ts
- [x] @aws-cdk-testing/framework-integ/test/aws-elasticsearch/test/integ.elasticsearch.custom-kms-key.ts
- [x] @aws-cdk-testing/framework-integ/test/aws-elasticsearch/test/integ.elasticsearch.unsignedbasicauth.ts
- [x] @aws-cdk-testing/framework-integ/test/aws-events-targets/test/logs/integ.log-group.ts
- [x] @aws-cdk-testing/framework-integ/test/aws-globalaccelerator-endpoints/test/integ.globalaccelerator.ts
- [x] @aws-cdk-testing/framework-integ/test/aws-logs-destinations/test/integ.lambda.ts
- [x] @aws-cdk-testing/framework-integ/test/aws-opensearchservice/test/integ.opensearch.custom-kms-key.ts
