### ISSUE TITLE
SDKv3-10: Update `aws-cdk` (CLI)

### ISSUE THREAD

**Issue by otaviomacedo** [aws/aws-cdk#31480]
### Context
The AWS SDK V2 is being deprecated. We need to remove all uses of it from the CDK.

### Task Description
Remove use of sdkv2 in `packages/aws-cdk`.

### Acceptance Criteria
-  All tests (unit and integ) pass using sdkv3.
-  No instances of sdkv2 are still in use in this package.

### Integration tests to write
- [x] Assume role with credentials from environment variables
- [x] Assume role with credentials from environment variables, using MFA
- [x] Credentials directly from environment variables
- [x] Credentials from Isengard plugin
- [x] Credentials from a generic plugin
- [x] Credentials from a process
- [x] Credentials from SSO
- [x] Credentials statically defined in the config
- [x] Credentials from Web identity
- [x] Credentials from an EC2 instance
- [x] Credentials from an ECS container

**Comment by HBobertz** [comment]
https://quip-amazon.com/KxMeA7P4ZWta/CDK-CLI-AWS-SDK-upgrade-to-v3
