### ISSUE TITLE
Graduate @aws-cdk/aws-kinesis to stable

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#5874]
We plan on graduating this module to `stable`.

### What does it mean?

It means we will start providing semantic versioning guarantees on the existing API's.

**Use this issue to provide feedback about the current API and any changes you think are warranted.**

Following are the tasks needed to complete before flipping the switch:

- [x] Validate no *p0* bugs in the last 4 weeks.
- [x] Validate L2 coverage.
- [x] Clear `awslint` exclusions (https://github.com/aws/aws-cdk/pull/6758)
- [x] Update `README` (#7038)
- [x] Retention period is not of `Duration` type (#7037)
- [x] Streams permissions is missing `ListShards` permissions (#6141)
- [x] Enable Stream Encryption by default (supported in all regions except `cn-north-1` and `cn-northwest-1` (#7102)
- [x] Update `grantxYz...` methods (i.e. take out `describeStream` and add `getShardIterator`) - added as a part of (#7037)
- [x] Conduct API review.

**Comment by richardhboyd** [comment]
I would recommend that we graduate specific Constructs to Stable. My biggest concern with Stable packages are two-fold: 
(1) If someone wants to add a new Construct to a package, it has to go from 0 to Stable in one PR without the benefit of an experimental period to test-drive the API. We're already seeing this in API Gateway
(2) the L1 Constructs are the most stable resources that exist in CDK. They should be marked as stable as soon as the cfn spec is processed.

**Comment by iliapolo** [comment]
@richardhboyd Wrote:

> I would recommend that we graduate specific Constructs to Stable. My biggest concern with Stable packages are two-fold:
(1) If someone wants to add a new Construct to a package, it has to go from 0 to Stable in one PR without the benefit of an experimental period to test-drive the API. We're already seeing this in API Gateway

You definitely make a good point. 

However, this graduation process reflects libraries we want to mark as stable given the current methodology, which is package wide. As it stands now, we allow for `experimental` Constructs or API to exist inside `stable` packages, by using the [`@experimental`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-codepipeline/lib/pipeline.ts#L91) annotation. This means that stability can be reached over a long period of time, with several PR's.

We are aware of the confusion this might create, and are already considering ways of resolving this. One way would be Construct level maturity, another is splitting experimental constructs to its own "*-experimental" package. 

In fact, we already have a pending [RFC](https://github.com/aws/aws-cdk-rfcs/blob/benisrae/v2.0/text/0079-cdk-v2.md#experimental-modules) that addresses this problem.
It would be great if you voice your concerns and provided feedback about this in the RFC.

@richardhboyd Wrote:

> (2) the L1 Constructs are the most stable resources that exist in CDK. They should be marked as stable as soon as the cfn spec is processed.

This depends on the maturity methodology we choose. L1 constructs are always auto-generated, and are therefore stable by nature. Do you feel this needs better clarification? Are users reluctant to use L1 constructs inside experimental packages for fear of API breakage?
