### ISSUE TITLE
📊Tracking: Step Functions

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#6489]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

The `@aws-cdk/aws-stepfunctions` package contains constructs for building serverless workflows using objects. Use this in conjunction with the `@aws-cdk/aws-stepfunctions-tasks` package, which contains classes used to integrate with other AWS services.

[AWS Docs](https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html)  

### Maturity: Experimental
See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

Open [issues](https://github.com/aws/aws-cdk/issues?q=is%3Aissue+is%3Aopen+step+functions+label%3Apackage%2Fstepfunctions)

### Implementation:

[CDK API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html) 

- [x] State Machine
- [x] Amazon States Language
- [x] Task Chaining
- [x] State Machine Fragments
- [x] Activity
- [x] Metrics
- [x] Validate IAM Policies that are generated by the `aws-stepfunctions` and `aws-stepfunctions-tasks` modules
- [x] Specify custom SFN state as JSON (escape hatch) (#7792)
- [x] Ability for tasks to bind state-level properties (eg, retry) (#6715) PR #7946 
- [x] Make Service Integration patterns consistent
  - [x] Glue (#8143)
  - [x] SNS (#7946)
  - [x] SQS (#7946)
  - [x] Lambda (#7946)
  - [x] Batch (#8115)
  - [x] Step Functions (#8178)
  - [x] DynamoDB (#8466)
  - [x] ECS (#8451)
  - [x] SageMaker - - Experimental as L2's for SageMaker don't exist yet
  - [x] EMR (#8177) - Experimental as L2's for EMR don't exist yet

### Issue list:

- [x] README updates (#7469)
- [x] Disambiguate mechanisms to invoke Lambda functions (#4801 )
- [x] Add logging configuration (#6933)
- [x]  Support JSONPath in Pass State Parameters (#7181) PR #8070 

--- 
This is a  📊Tracking Issue

**Comment by mariobittencourt** [comment]
Hi, I wonder how is the best way to track the progress/plans for further integrations. For example, to invoke an API Gateway from stepfunction.

**Comment by wong-a** [comment]
@mariobittencourt Check for open issues with the [@aws-cdk/aws-stepfunctions-tasks](https://github.com/aws/aws-cdk/issues?q=is%3Aopen+is%3Aissue+label%3A%40aws-cdk%2Faws-stepfunctions-tasks) label. There is already an issue tracking API Gateway support that has some PRs waiting for review. https://github.com/aws/aws-cdk/issues/11566

**Comment by mariobittencourt** [comment]
Thank you @wong-a. I started tracking them.
