### ISSUE TITLE
📊Tracking: AWS Config

### ISSUE THREAD

**Issue by ccfife** [aws/aws-cdk#6655]
Add your +1 👍  to help us prioritize high-level constructs for this service
--- 

### Overview:

Supported:
 - Config rules

Not supported:
- Configuration recorder
- Delivery channel
- Multi-account multi-region data aggregation

[AWS Docs](https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html)

### Maturity: Developer Preview
See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:
[AWS API Reference](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-config-readme.html)
- [x] Access Keys Rotated
- [x] CloudFormation Stack Drift Detection Check
- [x] CloudFormation Stack Notification Check
- [x] Custom Rule
- [x] Managed Rule

### Issue List
- [ ] https://github.com/aws/aws-cdk/issues/3492  Add support for Configuration recorder
- [ ] https://github.com/aws/aws-cdk/issues/3577  Add support for Delivery Channels

--- 
This is a  📊Tracking Issue

**Comment by iliapolo** [comment]
Hello everyone, we are about to graduate this module to `stable`. Yey!

Checkout https://github.com/aws/aws-cdk/issues/5872 to keep track and provide feedback :)
