### ISSUE TITLE
📊Tracking: migrating CloudFormation templates to the CDK

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#7837]
Add your +1 👍  to help us prioritize this feature!

---------------------------- 

### Overview:

We want to expand the capabilities of the `CfnInclude` class from the `core` package to allow retrieving and modifying the resources that form the template. Example experience:

```ts
import * as cfn_inc from '@aws-cdk/cloudformation-include';

const cfnTemplate = new cfn_inc.CfnInclude(this, 'Template', {
  templateFile: 'my-template.json',
});
const cfnBucket = cfnTemplate.getResource('Bucket') as s3.CfnBucket;

// now, we can modify the bucket, and all of those modifications will be reflected in the resulting template!
// for example, we can change its name
cfnBucket.bucketName = 'my-bucket-name';

// or, reference it in other constructs, including L2s
import * as iam from '@aws-cdk/aws-iam';

const role = new iam.Role(this, 'Role', {
  assumedBy: new iam.AnyPrincipal(),
});
role.addToPolicy(new iam.PolicyStatement({
  actions: ['s3:*'],
  resources: [cfnBucket.attrArn],
}));

// or, reference an L2 bucket from the L1
const bucket = s3.Bucket.fromBucketName(this, 'L2Bucket', cfnBucket.ref);
```

### Maturity: Experimental

See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.

### Implementation:

- [x] Support YAML templates in addition to JSON ones

- [x] Retrieving Resources by their logical ID
- [x] Retrieving Parameters by their logical ID
- [x] Retrieving Conditions by their logical ID
- [x] Retrieving Outputs by their logical ID

- [x] Support for the Properties CloudFormation resource attribute
- [x] Support for the Condition CloudFormation resource attribute
- [x] Support for the DependsOn CloudFormation resource attribute
- [x] Support for the CreationPolicy CloudFormation resource attribute
- [x] Support for the UpdatePolicy CloudFormation resource attribute
- [x] Support for the UpdateReplacePolicy CloudFormation resource attribute
- [x] Support for the DeletionPolicy CloudFormation resource attribute
- [x] Support for the Metadata CloudFormation resource attribute

- [ ] Full support for all CloudFormation functions
- [ ] Support nested Stacks

---------------------------- 

This is a  📊Tracking Issue

**Comment by skinny85** [comment]
This is the first Pull Request adding the `@aws-cdk/cloudformation-include` module to the CDK: #7304 .

**Comment by skinny85** [comment]
Second PR, adding support for the [`DependsOn` resource attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html): #7971

**Comment by skinny85** [comment]
The documentation for this feature can be found here: https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html

**Comment by Lock128** [comment]
Will thie feature also allow, when it is completed, to convert existing CFN templates to pure CDK code?

**Comment by Lock128** [comment]
Well, no, not exactly. That will most certainly be helpful.

But: We have a hell lot of CloudFormation already, this option would only give us the option to "keep" it and "adjust" it on the fly when using CDK.

If I want to go "all in" on CDK I would need an option to "transform" the CloudFormation code to CDK code (in whatever language).

**Comment by skinny85** [comment]
We have an (experimental) project that tries to generate code from your CloudFormation template: https://github.com/aws/aws-cdk/tree/master/packages/cdk-dasm#cdk-cloudformation-disassembler

@Lock128 can I ask you why do you think the approach I outlined above will not work for you? After you've included the CloudFormation template, you can go "all in" on CDK; the fact that there was a template there to start, instead of code, is not really important - it will be just an implementation detail hidden inside your Stacks.

I wonder what's your concern with doing the migration that way?

**Comment by Lock128** [comment]
Thanks for sharing the link, I wasn't aware of that project. That's what I was looking for ;)

The cocern I have:  it will essentially mean for us to keep the CloudFormation code "forever"..or until we migrate it...and do the enhancements in CDK... which is kind of ... weird...because it breaks languages "in the middle" :-)
But its a good starting point, definitely, I was not trying to narrow this down, please don't understand me wrong.

**Comment by ccfife** [comment]
Support importing a CloudFormation template in an AWS account from its ARN, in addition to importing templates from a local JSON/YAML file.

**Comment by nsutcliffe-speedline** [comment]
👍

**Comment by ajhool** [comment]
@skinny85 that disassembler would certainly help with cdk adoption and it feels like the right time to migrate from traditional cfn to cdk

**Comment by skinny85** [comment]
@ajhool the official way to migrate from CloudFormation to the CDK is to use the `cloudformation-include` module: https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html (blog article: https://aws.amazon.com/blogs/developer/migrating-cloudformation-templates-to-the-aws-cloud-development-kit).

Thanks,
Adam

**Comment by skinny85** [comment]
With release `1.77.0`, the `cloudformation-include` module is now Stable!

I'm resolving this issue - if you have a bug or feature request related to the module, please open us a separate issue. Thanks!
