### ISSUE TITLE
Graduate @aws-cdk/aws-cloudtrail to stable

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#8268]
SOP: https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md#entry-activities-3

This issue is tracking the graduation of the `@aws-cdk/aws-cloudtrail` module to stable API status.

Checklist items:
- [x] clear awslint exclusions where possible
- [x] No p0 bugs in the last 4 weeks - [query](https://github.com/aws/aws-cdk/issues?q=label%3A%40aws-cdk%2Faws-cloudtrail+label%3Ap0+created%3A%3C2020-05-31)
- [x] Fix most, if not all, p1 bugs - [query](https://github.com/aws/aws-cdk/issues?q=label%3A%40aws-cdk%2Faws-cloudtrail+label%3Ap1+created%3A%3C2020-05-31+)
- [x] Identify customer experiences that need improvement (consult module owner)
  - [x] Make onCloudTrailEvent a static method - https://github.com/aws/aws-cdk/pull/8076
  - [x] Modernize EventSelector APIs - https://github.com/aws/aws-cdk/pull/8097
  - [x] user specified log group - https://github.com/aws/aws-cdk/pull/8079
- [x] Refresh or update the `README.md` as needed.
- [x] Conduct API review
- [x] Complete any issues raised during API review
- [x] Graduate the module

**Comment by nija-at** [comment]
Graduation complete. Stable CloudTrail module released in [`1.46.0`](https://github.com/aws/aws-cdk/releases/tag/v1.46.0).
