### ISSUE TITLE
📊Tracking: [@aws-cdk/aws-appmesh] - AppMesh Stable Graduation

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk#9489]
We plan on graduating this module to `stable`.

### What does it mean?

It means we will start providing semantic versioning guarantees on the existing API's.

**Use this issue to provide feedback about the current API and any changes you think are warranted.**

Following are the tasks needed to complete before flipping the switch:

- [x] Validate no *p0* bugs in the last 4 weeks.
- [ ] Validate L2 coverage.
- [ ] Clear `awslint` exclusion
- [ ] Conduct API review.
- [ ] Audit README for accuracy
